### PR TITLE
docs: Hermes engine architecture design notes

### LINKED ISSUE #59: 🛠️ [TASK] : Low level doc for hermes engine mechanics
### Summary

Write a Low level doc about how hermes engine works.

### Description

Add a low level docs about the hermes engine, with detailed description how each component should work and which functionality it should has.
These docs should be added to the `docs/src/architecture/concepts` section.
Document should be written following this template https://docs.arc42.org/section-8/

### PR DESCRIPTION
**Pull request by Mr-Leshiy**
# Description

Hermes engine architecture design notes.
Updated sections:
- [solution strategy](https://input-output-hk.github.io/hermes/branch/feat_hermes_arc/architecture/04_solution_strategy/)
- [building blocks](https://input-output-hk.github.io/hermes/branch/feat_hermes_arc/architecture/05_building_block_view/hermes_core/)
- [cross cutting concepts](https://input-output-hk.github.io/hermes/branch/feat_hermes_arc/architecture/08_concepts/)

## Related Issue(s)

Closes #59

## Docs link

https://input-output-hk.github.io/hermes/branch/feat_hermes_arc/

### CODE REVIEW

**Review by alicechaitea — COMMENTED** [review]
Looks good to me!

**Review by cong-or — DISMISSED** [review]
lgtm

**Comment by Mr-Leshiy** [comment]
don't merge this PR

**Review by stevenj — APPROVED** [review]
The whole architecture is still WIP.
So, I am happy with this PR as is as a starting point.
We will be making subsequent revisions and trying to keep it DRY to make maintenance simpler.

**Pull request merged**
