### PR TITLE
docs: Adds notes on Hermes packaging requirements

### PR DESCRIPTION
**Pull request by saibatizoku**
# Description

Adds documentation requirements for packaging Hermes Applications.

## Related Issue(s)

List the issue numbers related to this pull request.

#70 

## Description of Changes

See the generated docs [here](https://input-output-hk.github.io/hermes/branch/feat_hermes_packaging_docs/architecture/08_concepts/hermes_packaging_requirements/overview/).

- [x] Overview
- [x] Packaging A Hermes Application
- [x] Defining Application Metadata
- [ ] Static Assets
- [ ] Application Data
- [ ] Application WASM Modules
- [ ] Application Signatures

## Please confirm the following checks

* [x] My code follows the style guidelines of this project
* [ ] I have performed a self-review of my code
* [ ] I have commented my code, particularly in hard-to-understand areas
* [x] I have made corresponding changes to the documentation
* [x] My changes generate no new warnings
* [ ] I have added tests that prove my fix is effective or that my feature works
* [ ] New and existing unit tests pass locally with my changes
* [ ] Any dependent changes have been merged and published in downstream module

### CODE REVIEW

**Review by Mr-Leshiy — DISMISSED** [review]
Looks awesome !

But I have a question about private and public data, maybe it make sense to rename directories to the `var/public` and `var/private` instead of `var/data`, `var/www` ?
So it will make it more clear and from the packaging perspective we will don't care what exact data should be there, we are just managing the scope to it.

cc @stevenj

**Comment by saibatizoku** [comment]
> Looks awesome !
> 
> But I have a question about private and public data, maybe it make sense to rename directories to the `var/public` and `var/private` instead of `var/data`, `var/www` ? So it will make it more clear and from the packaging perspective we will don't care what exact data should be there, we are just managing the scope to it.
> 
> cc @stevenj

Thanks! I'm open to renaming the paths, and I considered a similar approach to what you are proposing, but I think that `public` and `private` are terms that could lead to confusion, as they have different meanings depending on the context. 

In this case, the context is using HDF5 files as a file-system, so using `/var/data` and `/var/www`, is similar to the convention in POSIX-based file-systems that should be familiar to most developers.

So, in this case, I would opt for keeping the names as they are, or to find a middle ground.

**Review by FelipeRosa — APPROVED** [review]
LGTM

**Review by bkioshn — COMMENTED** [review]
Looks good, the document is clear and understandable 🥳

**Pull request merged**
